version: '3.9'

services:
  database:
    image: mysql
    container_name: bootcamp_cataline
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSOWORD: 'secret123'
      MYSQL_DATABASE: 'adonis'
    ports:
      - '3306:3306'
